# Generated by Django 5.0.1 on 2026-02-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ej: -34.6037', max_digits=9, null=True, verbose_name='latitud'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Ej: -58.3816', max_digits=9, null=True, verbose_name='longitud'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, verbose_name='biografía'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dni',
            field=models.CharField(max_length=20, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_plan',
            field=models.CharField(blank=True, max_length=100, verbose_name='plan'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='obra social/prepaga'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
    ]
