# Generated by Django 5.0.1 on 2026-02-13 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctor_latitude_doctor_longitude_alter_doctor_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código de 6 dígitos', max_length=6, verbose_name='código')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('expires_at', models.DateTimeField(verbose_name='expira en')),
                ('is_used', models.BooleanField(default=False, verbose_name='usado')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado en')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='dirección IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'verificación de email',
                'verbose_name_plural': 'verificaciones de email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'is_used'], name='users_email_code_ff90d2_idx'), models.Index(fields=['user', 'created_at'], name='users_email_user_id_61fb2b_idx')],
            },
        ),
    ]
