# Generated by Django 5.0.1 on 2026-02-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('patient', 'Paciente')], help_text='Tipo de cuenta seleccionado en registro. Se limpia al crear perfil.', max_length=10, null=True, verbose_name='tipo de cuenta'),
        ),
    ]
